name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Set Release Tag Name
        id: set-release-tag
        run: echo "release_tag=release-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Delete Existing Release (if any)
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.release_tag }}
        continue-on-error: true

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          release_name: Build Release ${{ github.run_id }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Linux
        run: npm run build:linux

      - name: Upload Linux Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_tag }}
          file: dist/*
          overwrite: true

      - name: Build for Windows
        run: npm run build:win

      - name: Upload Windows Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_tag }}
          file: dist/*
          overwrite: true

      - name: Build for Mac (Silicon)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --arm64

      - name: Upload Mac (Silicon) Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_tag }}
          file: dist/*
          overwrite: true

      - name: Build for Mac (Intel)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --x64

      - name: Upload Mac (Intel) Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_tag }}
          file: dist/*
          overwrite: true
