name: Build and Package

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare GitHub Release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.prepare.outputs.tag_name }}
    steps:
      - name: Set Release Tag Name
        id: prepare
        run: echo "tag_name=release-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Delete Existing Release (if any)
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/release-${{ github.run_id }}
        continue-on-error: true

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ github.run_id }}
          release_name: Build Release ${{ github.run_id }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Linux
        run: npm run build:linux

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
          file: dist/*
          overwrite: true

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Windows
        run: npm run build:win

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
          file: dist/*
          overwrite: true

  build-mac-silicon:
    name: Build for Mac (Silicon)
    runs-on: macos-latest
    needs: prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Mac (Silicon)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --arm64

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
          file: dist/*
          overwrite: true

  build-mac-intel:
    name: Build for Mac (Intel)
    runs-on: macos-latest
    needs: prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Mac (Intel)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --x64

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag_name }}
          file: dist/*
          overwrite: true
