name: Build and Package

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ github.run_id }}
          release_name: Build Release ${{ github.run_id }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Linux
        run: npm run build:linux

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: release-${{ github.run_id }}
          file: dist/*
          overwrite: true

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: create-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Windows
        run: npm run build:win

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: release-${{ github.run_id }}
          file: dist/*
          overwrite: true

  build-mac-silicon:
    name: Build for Mac (Silicon)
    runs-on: macos-latest
    needs: create-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Mac (Silicon)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --arm64

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: release-${{ github.run_id }}
          file: dist/*
          overwrite: true

  build-mac-intel:
    name: Build for Mac (Intel)
    runs-on: macos-latest
    needs: create-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build for Mac (Intel)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run build:mac -- --x64

      - name: Upload Artifact to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: release-${{ github.run_id }}
          file: dist/*
          overwrite: true
