package:
  name: Create Release and Upload Packages
  needs: [build-linux, build-windows, build-mac-silicon, build-mac-intel]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: 'v1.0.0'
        release_name: 'Release v1.0.0'
        body: |
          This release contains the latest builds for Linux, Windows, and macOS.
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Linux Build
      uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: ./linux

    - name: Upload Linux Build to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux
        asset_name: linux-build.zip
        asset_content_type: application/zip

    - name: Download Windows Build
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: ./windows

    - name: Upload Windows Build to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows
        asset_name: windows-build.zip
        asset_content_type: application/zip

    - name: Download Mac Silicon Build
      uses: actions/download-artifact@v3
      with:
        name: mac-silicon-build
        path: ./mac-silicon

    - name: Upload Mac Silicon Build to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mac-silicon
        asset_name: mac-silicon-build.zip
        asset_content_type: application/zip

    - name: Download Mac Intel Build
      uses: actions/download-artifact@v3
      with:
        name: mac-intel-build
        path: ./mac-intel

    - name: Upload Mac Intel Build to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mac-intel
        asset_name: mac-intel-build.zip
        asset_content_type: application/zip
